### ISSUE TITLE
How to remove the <Today> line?

### ISSUE THREAD

**Issue by leemoncn** [neuronetio/gantt-elastic#71]
How to remove the <Today> line? I don't want to display it.
![TIM图片20190807141715](https://user-images.githubusercontent.com/16697876/62599191-286e8580-b91e-11e9-931f-1c25f184d0de.png)

**Comment by neuronetio** [comment]
```css
.gantt-elastic__grid-line-time {
    display: none;
}
```
